module.exports = {
  UPDATE_MSID: 'UPDATE_MSID',
  RESET_MSID: 'RESET_MSID',
  //
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_WORLD_NAME: 'UPDATE_WORLD_NAME',
  RESET_EMAIL: 'RESET_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_WORLD_NAME: 'RESET_WORLD_NAME',
  //
  UPDATE_SESSION: 'UPDATE_SESSION',
  UPDATE_COOKIE: 'UPDATE_COOKIE',
  UPDATE_AGE: 'UPDATE_AGE',
  RESET_SESSION: 'RESET_SESSION',
  RESET_COOKIE: 'RESET_COOKIE',
  RESET_AGE: 'RESET_AGE',
  //
  UPDATE_STATE: 'UPDATE_STATE',
  RESET_STATE: 'RESET_STATE',
}
