module.exports = {
  UPDATE_EMAIL: 'UPATE_EMAIL',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_WORLD_NAME: 'UPDATE_WORLD_NAME',
  UPDATE_MSID: 'UPDATE_MSID',
  UPDATE_LOBBY_SESSION: 'UPDATE_LOBBY_SESSION',
  UPDATE_GAMEWORLD_SESSION: 'UPDATE_GAMEWORLD_SESSION',
  UPDATE_COOKIES: 'UPDATE_COOKIES',
  UPDATE_STATE: 'UPDATE_STATE',
  UPDATE_LOBBY_SESSION_AGE: 'UPDATE_LOBBY_SESSION_AGE',
  UPDATE_GAMEWORLD_SESSION_AGE: 'UPDATE_GAMEWORLD_SESSION_AGE',
}
